set term png large size 1920,1080

set title "\
    History of SCE Repo   \n\
r7:    2009-02-24 10:04:18\n\
r1094: 2018-06-11 15:45:39"

set xdata time
set timefmt "%s"
set xlabel "Date"

set output "files.png"
set ylabel "#files"
plot "sce-dev.dat" using 2:3 w boxes lw 3 title "#files"

set output "code.png"
set ylabel "#loc"
plot "sce-dev.dat" using 2:4 w l lw 3 title "#blank" , '' u 2:5 w l lw 3 title "#comment", '' u 2:6 w steps lw 3 title "#code"

